/**
 * SCRIPT DE CRIAÇÃO DO BANCO PARA O SISTEMA DE TRANSPORTE E GERENCIAMENTO DE CUSTOS
 * ALOCADO AO DESLOCAMENTO DE VEICULOS DA TRANSPORTADORA.
 * @author KAIRO RODRIGUES DOS SANTOS EMAIL: kairord@gmail.com
 *		   LAIS COL 				  EMAIL: 
 */

/** CRIA O BANCO DE DADOS CHAMADO DE TRANSPORTADORA **/
CREATE DATABASE TRANSPORTADORA;

/** SELECIONA O BANCO TRANSPORTADORA PARA PODER SER CRIADO AS RESPECTIVAS TABELAS **/
USE TRANSPORTADORA;

/**
 * A TABELA TIPO DE CAMINHAO É CRIADO COM O OBJETIVO DE ESPECIFICAR O PESO MAXIMO SUPORTADO 
 * DE ACORDO COM A SUA DESCRIÇÃO (O TAMANHO,EIXO) DOS CAMINHOES JA EXISTENTES NO MERCADO DE
 * TRANSPORTE.
 * UM EXEMPLO DESTA TABELA, PODEMOS FORMULAR QUE UM CAMINHA TOCO OU SEMI-PESADO REPRESENTANDO
 * UMA DESCRICAO PODE PESAR NO MAXIMO 7 TONELADAS (PESO-SUPORTADO)
 */
CREATE TABLE TIPO_CAMINHAO(
ID INT PRIMARY KEY AUTO_INCREMENT,
DESCRICAO VARCHAR(100),
PESO_MAXIMO_SUPORTADO DECIMAL(10,2)
);


CREATE TABLE CAMINHAO(
ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
TIPO_CAMINHAO INT,
TIPO_CARGA VARCHAR(100),
ESTADO_CAMINHAO ENUM('PARADO','VIAGEM') DEFAULT 'PARADO',
FOREIGN KEY (TIPO_CAMINHAO) REFERENCES TIPO_CAMINHAO(ID)
);
SELECT * FROM TIPO_CAMINHAO;

CREATE TABLE VIAGEM_IDA
(
ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
ID_CAMINHAO INT,
QTD_COMBUSTIVEL INT,
CUSTO_COMBUSTIVEL DECIMAL(5,2),
TEMPO_VIAGEM INT,
CIDADE_IDA VARCHAR(50),
DATA_IDA DATE,
FOREIGN KEY (ID_CAMINHAO) REFERENCES CAMINHAO(ID)
);

CREATE TABLE VIAGEM_VOLTA
(
ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
ID_CAMINHAO INT,
QTD_COMBUSTIVEL INT,
CUSTO_COMBUSTIVEL DECIMAL(5,2),
TEMPO_VIAGEM INT,
CIDADE_VOLTA VARCHAR(50),
DATA_VOLTA DATE,
FOREIGN KEY (ID_CAMINHAO) REFERENCES CAMINHAO(ID)
);

